name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-10"

[[d1_databases]]
binding = "DB"
database_name = "qrcode_hub"
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
database_id = "8ab66f3d-64f3-4b57-b8bf-97d0be19f7ea"

[triggers]
crons = ["0 2 */1 * *"]

[[env.dev.d1_databases]]
binding = "DB"
database_name = "qrcode_hub"
database_id = "8ab66f3d-64f3-4b57-b8bf-97d0be19f7ea"

# [env.dev.triggers]
# crons = ["*/10 * * * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"

[env.dev.vars]
ADMIN_PASSWORD = "Wsad1234"  # 开发环境密码